{% set name = "caelus" %}
{% set version = "3.0.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/sayerhs/cpl/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16d24b1a3dbffb0fbf10b853c0c23b757384e33a61b305b479ab217f1731dea3

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - caelus = caelus.scripts.caelus:main
    - caelus_tutorials = caelus.scripts.caelus_tutorials:main
    - caelus_sim = caelus.scripts.caelus_sim:main


requirements:
  host:
    - python >=3.10
    - pip
    - setuptools

  run:
    - python >=3.10
    - six
    - numpy
    - matplotlib-base
    - pyyaml
    - ply
    - pytz
    - jinja2
    - vtk
    - pyvista
    - pandas
    - scipy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - caelus

about:
  home: https://github.com/sayerhs/cpl/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'Python library for use with Caelus CML and OpenFOAM'
  doc_url: https://caelus.readthedocs.io/
  dev_url: https://github.com/sayerhs/cpl

extra:
  recipe-maintainers:
    - sayerhs
    - cnsidero
